language: node_js
sudo: false
node_js:
- '6'
- '7'
- '8'
before_install:
- sudo apt-get install graphicsmagick
deploy:
  provider: npm
  email: shekhei@gmail.com
  api_key:
    secure: cIJah+jsKj8Y5hxjQzaGdC7kG9RaslmMHHnGabxlM9Qq8W4JGwm1U2peXJY+Ts1phn/toBSaN6thP8XhwgmZbMkrLhG6tHwU9fHqQUACubpBFxwbE1cbNx+Jc8yyjJkcq2M4DibLPwhJ2RhFi4sJ/2ItNSk9RC+EFIvGdq+HEFo/PMWCar2ALMPdS2rEpbfTkNBoitfVeCuYUb1e3cjsC1S0R0Dc4VcFOvWSyvnmidvjSCJcyYvnhwlD5Gknghvz3qFHQfd3h280Jqb/oUqM67vr0hzGRqZbYCIbRVYS4WfAfWaT8WPZuOsi4tW2EGa+4mNm0DMZANFA3r4DIzILgEUvHrij+kZMlSauaH+cWOUW8nfAQ6gFTH3XNQXxk+B/904qxZ1gxrMP5or6g4fBLdnHk+BKXIKr/XQF8zavZpKSHf35w87JyiHxux4ar+qd+FRTsNsqg9j427B3dkJmk5/vccAhVO/dtY4dzS/i/wG6mzFJDYnJqDJAFrnzDv2Zl5SF1Tiu3P1kSFPqeQQdAUdeLlaWgD33PjC2fqJVLvww4NJaq1S8JpXuoCYB82iVHO1z9B/v02FnF1GE5NcUDuD3J+nO1a6O8tTfXbRDSCoq98LT7cmZ3+OL3IqY0lCGp8h+CuPYz7EOrj2KZeXxxrKHDICisX+N6Yo1GJUbc2Y=
  on:
    tags: true
